version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - '4000:4000'
    env_file:
      - ./packages/api/.env
    depends_on:
      - db

  indexer:
    build:
      context: .
      dockerfile: packages/indexer/Dockerfile
    env_file:
      - ./packages/indexer/.env
    depends_on:
      - db

  db:
    image: timescale/timescaledb:2.14.2-pg16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./packages/indexer/scripts:/docker-entrypoint-initdb.d

  client:
    build:
      context: .
      dockerfile: packages/client/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Exclude node_modules from host volume
    environment:
      - NODE_ENV=production # Or development for hot-reloading
