name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract tags
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
          echo "date_tag=$(date +%F)" >> "$GITHUB_OUTPUT"

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/api/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pokt-metrics-api:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/pokt-metrics-api:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/pokt-metrics-api:${{ steps.vars.outputs.date_tag }}

      - name: Build and push Indexer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./packages/indexer/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/pokt-metrics-indexer:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/pokt-metrics-indexer:${{ steps.vars.outputs.sha_short }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/pokt-metrics-indexer:${{ steps.vars.outputs.date_tag }}
